//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMember
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iSpan_ProjectEntities1 : DbContext
    {
        public iSpan_ProjectEntities1()
            : base("name=iSpan_ProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessImg> BusinessImg { get; set; }
        public virtual DbSet<BusinessMember> BusinessMember { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<NormalMember> NormalMember { get; set; }
        public virtual DbSet<OptionsToProducts> OptionsToProducts { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payment_Term> Payment_Term { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductImg> ProductImg { get; set; }
        public virtual DbSet<ProductOptionGroup> ProductOptionGroup { get; set; }
        public virtual DbSet<ProductOptions> ProductOptions { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<View_OrderDetail_with_OptionGroupName> View_OrderDetail_with_OptionGroupName { get; set; }
        public virtual DbSet<View_showProductList> View_showProductList { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
