//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderDetail_with_OptionGroupName
    {
        public Nullable<int> Order_fid { get; set; }
        public int OrderItem_id { get; set; }
        public Nullable<int> Product_fid { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Qty { get; set; }
        public string OptionGroupName { get; set; }
        public string OptionName { get; set; }
    }
}
