//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSPanProjectDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessMember()
        {
            this.Orders = new HashSet<Orders>();
            this.Orders1 = new HashSet<Orders>();
            this.Payment_Term = new HashSet<Payment_Term>();
            this.ProductOptionGroup = new HashSet<ProductOptionGroup>();
            this.Products = new HashSet<Products>();
        }
    
        public int fid { get; set; }
        public string MemberName { get; set; }
        public string MemberID { get; set; }
        public string Password { get; set; }
        public string Brand { get; set; }
        public string ShopType { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
        public string OffDay { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> DeliveryAmount { get; set; }
        public Nullable<byte> isPlasticBag { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<int> CashPaymentLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Term> Payment_Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOptionGroup> ProductOptionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
