//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSPanProjectDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessImg
    {
        public int fid { get; set; }
        public Nullable<int> B_fid { get; set; }
        public string LOGO_ImgPath { get; set; }
        public string SIgh_ImgPath { get; set; }
        public string Banner_ImgPath_1 { get; set; }
        public string Banner_ImgPath_2 { get; set; }
        public string Banner_ImgPath_3 { get; set; }
    }
}
