//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSPanProjectDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int fid { get; set; }
        public Nullable<int> N_fid { get; set; }
        public Nullable<int> B_fid { get; set; }
        public string B_MemberName { get; set; }
        public string B_MemberPhone { get; set; }
        public string PickUpDate { get; set; }
        public string PickUpTime { get; set; }
        public string PickUpType { get; set; }
        public string PlasticBag { get; set; }
        public string PickUpPerson { get; set; }
        public string PickUpPerson_Phone { get; set; }
        public string PaymentTerm { get; set; }
        public string TaxIDNum { get; set; }
        public string OrderState { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public string OrderSN { get; set; }
        public string OrderPrefix { get; set; }
        public string Order_Detele { get; set; }
    
        public virtual BusinessMember BusinessMember { get; set; }
        public virtual BusinessMember BusinessMember1 { get; set; }
        public virtual NormalMember NormalMember { get; set; }
        public virtual NormalMember NormalMember1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
